### PR TITLE
H2 for all sidebar headers

### PR DESCRIPTION
**Pull request by danielmrey**
I think is better if sidebar headers are H2

### CODE REVIEW

**Comment by SimonPadbury** [comment]
I have allowed this, not I don't understand why you want the sidebar headers to be h2. How is that not bad for SEO, when surely the sidebars are less important than the article itself?

**Comment by danielmrey** [comment]
We spoke about this long time ago.

1 > There has to be one H1 per page
2 > Then in order and with no gaps from H1, H2, H3, H4, H5 and H6
3 > Headers are nested, so H2 belongs to H1, H3 belongs to H2 and then to
H1, etc...

If you put H4 in sidebar you break 2 rules

A > Unless you put H2 and H3 in the body you break rule 2
B > And even if rule A is achieved maybe Sidebar information does not belog
to that thread H1 > H2 > H3 > H4 Sidebar that breaks rules 3

Having H2 in sidebar opens a new piece of information or Article
independent of other parts... We can style this differently to the H2 in
Main:

.main-contents h2 {rule;}
.sidebar-contents h2 {rule;}



Thank you.

Best Regards.

*Daniel Muñoz Rey*
Web Developer
+44 (0)776 517 0430
www.danielmrey.com
info@danielmrey.com

The information transmitted is intended only for the recipient to which it
is addressed, any use by others is prohibited. If you received this in
error, please contact the sender on info@danielmrey.com and delete the
material from any computer. Thank you.

**Comment by SimonPadbury** [comment]
Like I said, I allowed it but I am not convinced. The sidebar and footer headers look too massive.

**Comment by danielmrey** [comment]
The important thing is that they are correct for SEO

If the fonts are massive just adjust the styling very easily:

.sidebar h2 {rule;}
.footer h2 {rule;}

But Simon if you are not convinced then don't do it... I would do it then
in my child...

Thank you.

Best Regards.

*Daniel Muñoz Rey*
Web Developer
+44 (0)776 517 0430
www.danielmrey.com
info@danielmrey.com

The information transmitted is intended only for the recipient to which it
is addressed, any use by others is prohibited. If you received this in
error, please contact the sender on info@danielmrey.com and delete the
material from any computer. Thank you.

**Comment by SimonPadbury** [comment]
No, as I said, I have allowed it, bowing to you r better judgment.

It just looks silly.

**Comment by danielmrey** [comment]
Thank you for trusting mu judjement but If it just looks silly change the
CSS rules:

.sidebar h2 {rule;}
.footer h2 {rule;}

And if you are not happy then revert it... This is your project and you
must be happy with it!

Thank you.

Best Regards.

*Daniel Muñoz Rey*
Web Developer
+44 (0)776 517 0430
www.danielmrey.com
info@danielmrey.com

The information transmitted is intended only for the recipient to which it
is addressed, any use by others is prohibited. If you received this in
error, please contact the sender on info@danielmrey.com and delete the
material from any computer. Thank you.

**Pull request merged**
